#TABUADA DE UM NÚMERO
#DESAFIIO 07
print('DESAFIO 07')
tabu= int(input('Digite um número para ver sua tabuada: '))
print ('__' *8)
print('{} x {:2} = {}'.format(tabu, 1, tabu*1))
print('{} x {:2} = {}'.format(tabu, 2, tabu*2))
print('{} x {:2} = {}'.format(tabu, 3, tabu*3))
print('{} x {:2} = {}'.format(tabu, 4, tabu*4))
print('{} x {:2} = {}'.format(tabu, 5, tabu*5))
print('{} x {:2} = {}'.format(tabu, 6, tabu*6))
print('{} x {:2} = {}'.format(tabu, 7, tabu*7))
print('{} x {:2} = {}'.format(tabu, 8, tabu*8))
print('{} x {:2} = {}'.format(tabu, 9, tabu*9))
print('{} x {} = {}'  .format(tabu, 10, tabu*10))
print ('__' *8)